### ISSUE TITLE
Invite Request and Question

### ISSUE THREAD

**Issue by honzi** [gamedev/invites#23]
Hey @r-lyeh and gamedevs. I'd like to join! I can provide my coding "skills", love for open source, and obsession with keeping my GitHub streak going. Is the organization still alive?

The question is regarding leadership of the organization. You mentioned in the reddit post that it may be for moderators of the subreddit only? I can help run the organization if needed, but alas I am just a simple reddit lurker.

**Comment by r-lyeh** [comment]
There is no much interest in this anymore.

As something to do, I'd like to use discord instead (as a chat room), and fork finished/interesting projects of us from here (some kind of "publishing" action from the group).

Feel free to discuss :)

**Comment by r-lyeh** [comment]
Another thing to do is to remove the 'per language' categories.
I'd rather stick to none :)

**Comment by honzi** [comment]
I'm sure it could be possible to revive interest somehow. Discord looks good to me and might help with that. Is there already a server set up?

Are the organization groups the `per language` categories you are referring to? Those could be reworked on a per-repository basis for people interested in specific projects. I also noticed that they are secret (when I don't think they should be so people can more easily find ones to join) and that there is a redundant `Owners` group (which GitHub replaced with the owners role).

I can also provide a private repository for the organization to use.

**Comment by r-lyeh** [comment]
Sure thing, https://discord.gg/0fTHx64VxeGgjBvj 

I mean, I've experienced this in other gamedev orgs as well. The per language category is mostly an error: C, C++, Javascript, Lua, etc. Most of the rooms will be with 1 or 2 users. It's much more practical splitting gamedev by context, common to all languages: AI & Behavior, Sound & Music, Data de/encoding, Animation, GameObjects, Spatial Partioning, World/Level streaming, etc

I think we should remove all programming groups from the github org for now.
I'd rather stick to the discord chat as a base to model the organization instead.
Its much quickier to add/remove channels, and we can see quickly if there are any interest in the recently created groups or none at all :)

Sounds good enough?

**Comment by honzi** [comment]
Agreed, that makes sense to me. It's a shame GitHub moved away from these Discord-esque features, otherwise it could have been a better organization experience.
